
using Contensive.BaseClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static Contensive.Addons.ContactManagerTools.Controllers.GenericController;
using static Contensive.Addons.ContactManagerTools.Constants;
using static Contensive.Addons.ContactManagerTools.HtmlController;

namespace Contensive.Addons.ContactManagerTools {
    public static  class AdminUIController {
        public enum SortingStateEnum {
            NotSortable = 0,
            SortableSetAZ = 1,
            SortableSetza = 2,
            SortableNotSet = 3
        }
        //
        //====================================================================================================
        //   Report Cell Header
        //       ColumnPtr       :   0 based column number
        //       Title
        //       Width           :   if just a number, assumed to be px in style and an image is added
        //                       :   if 00px, image added with the numberic part
        //                       :   if not number, added to style as is
        //       align           :   style value
        //       ClassStyle      :   class
        //       RQS
        //       SortingState
        //
        public static string getReport_CellHeader( int ColumnPtr, string Title, string Width, string Align, string ClassStyle, string RefreshQueryString, SortingStateEnum SortingState) {
            try {
                if (string.IsNullOrEmpty(Title)) Title = "&nbsp;";
                string Style = "VERTICAL-ALIGN:bottom;";
                if (!string.IsNullOrEmpty(Align)) Style += "TEXT-ALIGN:" + Align + ";";
                if (!string.IsNullOrEmpty(Width)) Style = Style + "width:" + Width + ";";
                string QS = "";
                switch (SortingState) {
                    case SortingStateEnum.SortableNotSet:
                        QS = modifyQueryString(RefreshQueryString, "ColSort", ((int)SortingStateEnum.SortableSetAZ).ToString(), true);
                        QS = modifyQueryString(QS, "ColPtr", ColumnPtr.ToString(), true);
                        Title = "<a href=\"?" + QS + "\" title=\"Sort A-Z\" class=\"ccAdminListCaption\">" + Title + "</a>";
                        break;
                    case SortingStateEnum.SortableSetza:
                        QS = modifyQueryString(RefreshQueryString, "ColSort", ((int)SortingStateEnum.SortableSetAZ).ToString(), true);
                        QS = modifyQueryString(QS, "ColPtr", ColumnPtr.ToString(), true);
                        Title = "<a href=\"?" + QS + "\" title=\"Sort A-Z\" class=\"ccAdminListCaption\">" + Title + "<i title=\"down\" class=\"fas fa-arrow-circle-up\"></i>";
                        break;
                    case SortingStateEnum.SortableSetAZ:
                        QS = modifyQueryString(RefreshQueryString, "ColSort", ((int)SortingStateEnum.SortableSetza).ToString(), true);
                        QS = modifyQueryString(QS, "ColPtr", ColumnPtr.ToString(), true);
                        Title = "<a href=\"?" + QS + "\" title=\"Sort Z-A\" class=\"ccAdminListCaption\">" + Title + "<i title=\"down\" class=\"fas fa-arrow-circle-down\"></i>";
                        break;
                }
                return "<td style=\"" + Style + "\" class=\"" + ClassStyle + "\">" + Title + "</td>";
            } catch (Exception) {
                throw;
            }
        }
        //
        //====================================================================================================
        /// <summary>
        /// returns the integer column ptr of the column last selected
        /// </summary>
        /// <param name="core"></param>
        /// <param name="DefaultSortColumnPtr"></param>
        /// <returns></returns>
        public static int getReportSortColumnPtr(CPBaseClass cp, int DefaultSortColumnPtr) {
            //
            string VarText = cp.Doc.GetText("ColPtr");
            int tempGetReportSortColumnPtr = cp.Utils.EncodeInteger(VarText);
            if ((tempGetReportSortColumnPtr == 0) && (VarText != "0")) {
                tempGetReportSortColumnPtr = DefaultSortColumnPtr;
            }
            return tempGetReportSortColumnPtr;
        }
        //
        //====================================================================================================
        //   Get Sort Column Type
        //
        //   returns the integer for the type of sorting last requested
        //       0 = nothing selected
        //       1 = sort A-Z
        //       2 = sort Z-A
        //
        //   Orderby is generated by the selection of headers captions by the user
        //   It is up to the calling program to call GetReportOrderBy to get the orderby and use it in the query to generate the cells
        //   This call returns a comma delimited list of integers representing the columns to sort
        //
        public static int getReportSortType(CPBaseClass cp) {
            //
            string VarText = cp.Doc.GetText("ColPtr");
            int tempGetReportSortType;
            if ((cp.Utils.EncodeInteger(VarText) != 0) || (VarText == "0")) {
                //
                // A valid ColPtr was found
                //
                tempGetReportSortType = cp.Doc.GetInteger("ColSort");
            } else {
                tempGetReportSortType = (int)SortingStateEnum.SortableSetAZ;
            }
            return tempGetReportSortType;
        }
        public static string kmaStartTableCell(string widthPercent ) {
            return "<td width=\"" + widthPercent + "\">";
        }
        ////
        ////
        ////====================================================================================================
        //public static string getReport(CPBaseClass cp, int RowCount, string[] ColCaption, string[] ColAlign, string[] ColWidth, string[,] Cells, int PageSize, int PageNumber, string PreTableCopy, string PostTableCopy, int DataRowCount, string ClassStyle) {
        //    try {
        //        int ColCnt = Cells.GetUpperBound(1);
        //        bool[] ColSortable = new bool[ColCnt + 1];
        //        for (int Ptr = 0; Ptr < ColCnt; Ptr++) {
        //            ColSortable[Ptr] = false;
        //        }
        //        //
        //        return getReport2(cp, RowCount, ColCaption, ColAlign, ColWidth, Cells, PageSize, PageNumber, PreTableCopy, PostTableCopy, DataRowCount, ClassStyle, ColSortable, 0);
        //    } catch (Exception) {
        //        throw;
        //    }
        //}
        //
        //====================================================================================================
        public static string getReport2(CPBaseClass cp, int RowCount, string[] ColCaption, string[] ColAlign, string[] ColWidth, string[,] Cells, int PageSize, int PageNumber, string PreTableCopy, string PostTableCopy, int DataRowCount, string ClassStyle, bool[] ColSortable, int DefaultSortColumnPtr) {
            string result = "";
            try {
                string RQS = null;
                int RowBAse = 0;
                var Content = new StringBuilder();
                var Stream = new StringBuilder();
                int ColumnCount = 0;
                int ColumnPtr = 0;
                string ColumnWidth = null;
                int RowPointer = 0;
                string WorkingQS = null;
                //
                int PageCount = 0;
                int pagePtr = 0;
                int LinkCount = 0;
                int ReportPageNumber = 0;
                int ReportPageSize = 0;
                string iClassStyle = null;
                int SortColPtr = 0;
                int SortColType = 0;
                //
                ReportPageNumber = PageNumber;
                if (ReportPageNumber == 0) {
                    ReportPageNumber = 1;
                }
                ReportPageSize = PageSize;
                if (ReportPageSize < 1) {
                    ReportPageSize = 50;
                }
                //
                iClassStyle = ClassStyle;
                if (string.IsNullOrEmpty(iClassStyle)) {
                    iClassStyle = "ccPanel";
                }
                //If IsArray(Cells) Then
                ColumnCount = Cells.GetUpperBound(1);
                //End If
                RQS = cp.Doc.RefreshQueryString;
                //
                SortColPtr = getReportSortColumnPtr(cp, DefaultSortColumnPtr);
                SortColType = getReportSortType(cp);
                //
                // ----- Start the table
                //
                Content.Append(HtmlController.tableStart(3, 1, 0));
                //
                // ----- Header
                //
                Content.Append("\r\n<tr>");
                Content.Append(getReport_CellHeader( 0, "&nbsp", "50px", "Right", "ccAdminListCaption", RQS, SortingStateEnum.NotSortable));
                for (ColumnPtr = 0; ColumnPtr < ColumnCount; ColumnPtr++) {
                    ColumnWidth = ColWidth[ColumnPtr];
                    if (!ColSortable[ColumnPtr]) {
                        //
                        // not sortable column
                        //
                        Content.Append(getReport_CellHeader( ColumnPtr, ColCaption[ColumnPtr], ColumnWidth, ColAlign[ColumnPtr], "ccAdminListCaption", RQS, SortingStateEnum.NotSortable));
                    } else if (ColumnPtr == SortColPtr) {
                        //
                        // This is the current sort column
                        //
                        Content.Append(getReport_CellHeader( ColumnPtr, ColCaption[ColumnPtr], ColumnWidth, ColAlign[ColumnPtr], "ccAdminListCaption", RQS, (SortingStateEnum)SortColType));
                    } else {
                        //
                        // Column is sortable, but not selected
                        //
                        Content.Append(getReport_CellHeader( ColumnPtr, ColCaption[ColumnPtr], ColumnWidth, ColAlign[ColumnPtr], "ccAdminListCaption", RQS, SortingStateEnum.SortableNotSet));
                    }

                    //If ColumnPtr = SortColPtr Then
                    //    '
                    //    ' This column is currently the active sort
                    //    '
                    //    Call Content.Append(GetReport_CellHeader(ColumnPtr, ColCaption(ColumnPtr), ColumnWidth, ColAlign(ColumnPtr), "ccAdminListCaption", RQS, SortColType))
                    //Else
                    //    Call Content.Append(GetReport_CellHeader(ColumnPtr, ColCaption(ColumnPtr), ColumnWidth, ColAlign(ColumnPtr), "ccAdminListCaption", RQS, SortingStateEnum.SortableNotSet))
                    //End If
                }
                Content.Append("\r\n</tr>");
                //
                // ----- Data
                //
                if (RowCount == 0) {
                    Content.Append("\r\n<tr>");
                    Content.Append(getReport_Cell( (RowBAse + RowPointer).ToString(), "right", 1, RowPointer));
                    Content.Append(getReport_Cell( "-- End --", "left", ColumnCount, 0));
                    Content.Append("\r\n</tr>");
                } else {
                    RowBAse = (ReportPageSize * (ReportPageNumber - 1)) + 1;
                    for (RowPointer = 0; RowPointer < RowCount; RowPointer++) {
                        Content.Append("\r\n<tr>");
                        Content.Append(getReport_Cell( (RowBAse + RowPointer).ToString(), "right", 1, RowPointer));
                        for (ColumnPtr = 0; ColumnPtr < ColumnCount; ColumnPtr++) {
                            Content.Append(getReport_Cell( Cells[RowPointer, ColumnPtr], ColAlign[ColumnPtr], 1, RowPointer));
                        }
                        Content.Append("\r\n</tr>");
                    }
                }
                //
                // ----- End Table
                //
                Content.Append(Constants.kmaEndTable);
                result += Content.ToString();
                //
                // ----- Post Table copy
                //
                PageCount = 1;
                if (DataRowCount > 0) {
                    PageCount = 1 + cp.Utils.EncodeInteger(((double)DataRowCount-1.0) / (double)ReportPageSize);
                }
                //if ((DataRowCount / (double)ReportPageSize) != Math.Floor((DataRowCount / (double)ReportPageSize))) {
                //    PageCount = 1 + encodeInteger(((double)DataRowCount / (double)ReportPageSize) + 0.5);
                //} else {
                //    PageCount = 1 + encodeInteger(DataRowCount / (double)ReportPageSize);
                //}
                if (PageCount > 1) {
                    result += "<div class=\"small mt-4\">Page " + ReportPageNumber + " (Row " + (RowBAse) + " of " + DataRowCount + ")</div>";
                    if (PageCount > 20) {
                        pagePtr = ReportPageNumber - 10;
                    }
                    if (pagePtr < 1) {
                        pagePtr = 1;
                    }
                    if (PageCount > 1) {
                        result += "<div class=\"small my-4\">Go to Page ";
                        if (pagePtr != 1) {
                            WorkingQS = cp.Doc.RefreshQueryString;
                            WorkingQS = modifyQueryString(WorkingQS, "GotoPage", "1", true);
                            result += "<a class=\"mx-1 p-2 border\" href=\"?" + WorkingQS + "\">1</A>...&nbsp;";
                        }
                        WorkingQS = cp.Doc.RefreshQueryString;
                        WorkingQS = modifyQueryString(WorkingQS, RequestNamePageSize, ReportPageSize.ToString(), true);
                        while ((pagePtr <= PageCount) && (LinkCount < 20)) {
                            if (pagePtr == ReportPageNumber) {
                                result += "<span class=\"mx-1 p-2 border\" >" + pagePtr + "</span>";
                            } else {
                                WorkingQS = modifyQueryString(WorkingQS, RequestNamePageNumber, pagePtr.ToString(), true);
                                result += "<a class=\"mx-1 p-2 border\" href=\"?" + WorkingQS + "\">" + pagePtr + "</A>";
                            }
                            pagePtr++;
                            LinkCount++;
                        }
                        if (pagePtr < PageCount) {
                            WorkingQS = modifyQueryString(WorkingQS, RequestNamePageNumber, PageCount.ToString(), true);
                            result += "...<a class=\"mx-1 p-2 border\" href=\"?" + WorkingQS + "\">" + PageCount + "</A>";
                        }
                        if (ReportPageNumber < PageCount) {
                            WorkingQS = modifyQueryString(WorkingQS, RequestNamePageNumber, (ReportPageNumber + 1).ToString(), true);
                            result += "...<a class=\"mx-1 p-2 border\" href=\"?" + WorkingQS + "\">next</A>";
                        }
                        result += "</div>";
                    }
                }
                return PreTableCopy + result + PostTableCopy;
                ////
                //result = ""
                //+ PreTableCopy + "<table border=0 cellpadding=0 cellspacing=0 width=\"100%\"><tr><td style=\"padding:10px;\">"
                //+ result + "</td></tr></table>"
                //+ PostTableCopy + "";
            } catch (Exception) {
                throw;
            }
            //return result;
        }
        //
        //====================================================================================================
        public static string getReport_Cell( string copy, string align, int columns, int rowPointer) {
            string result = "\r\n<td valign=\"middle\" align=\"" + align + "\"";
            result += ((rowPointer % 2) > 0) ? " class=\"ccAdminListRowOdd\"" : " class=\"ccAdminListRowEven\"";
            result += (align.Equals("right")) ? " style=\"text-align:right\"" : (align.Equals("center")) ? " style=\"text-align:center\"" : " style=\"text-align:left\"";
            result += (columns > 1) ? " colspan=\"" + columns + "\"" : "";
            return result + ">" + ((String.IsNullOrWhiteSpace(copy)) ? "&nbsp;" : copy) + "</td>";
        }
        //
        ////====================================================================================================
        //public static string getReport(CPBaseClass cp, int RowCount, string[] ColCaption, string[] ColAlign, string[] ColWidth, string[,] Cells, int PageSize, int PageNumber, string PreTableCopy, string PostTableCopy, int DataRowCount, string ClassStyle) {
        //    string result = "";
        //    try {
        //        int ColCnt = Cells.GetUpperBound(1);
        //        bool[] ColSortable = new bool[ColCnt + 1];
        //        for (int Ptr = 0; Ptr < ColCnt; Ptr++) {
        //            ColSortable[Ptr] = false;
        //        }
        //        //
        //        result = getReport2(cp, RowCount, ColCaption, ColAlign, ColWidth, Cells, PageSize, PageNumber, PreTableCopy, PostTableCopy, DataRowCount, ClassStyle, ColSortable, 0);
        //    } catch (Exception ex) {

        //    }
        //    return result;
        //}
        ////
        ////====================================================================================================
        //public static string getReport2(CPBaseClass cp, int RowCount, string[] ColCaption, string[] ColAlign, string[] ColWidth, string[,] Cells, int PageSize, int PageNumber, string PreTableCopy, string PostTableCopy, int DataRowCount, string ClassStyle, bool[] ColSortable, int DefaultSortColumnPtr) {
        //    string result = "";
        //    try {
        //        string RQS = null;
        //        int RowBAse = 0;
        //        var Content = new StringBuilder();
        //        var Stream = new StringBuilder();
        //        int ColumnCount = 0;
        //        int ColumnPtr = 0;
        //        string ColumnWidth = null;
        //        int RowPointer = 0;
        //        string WorkingQS = null;
        //        //
        //        int PageCount = 0;
        //        int PagePointer = 0;
        //        int LinkCount = 0;
        //        int ReportPageNumber = 0;
        //        int ReportPageSize = 0;
        //        string iClassStyle = null;
        //        int SortColPtr = 0;
        //        int SortColType = 0;
        //        //
        //        ReportPageNumber = PageNumber;
        //        if (ReportPageNumber == 0) {
        //            ReportPageNumber = 1;
        //        }
        //        ReportPageSize = PageSize;
        //        if (ReportPageSize < 1) {
        //            ReportPageSize = 50;
        //        }
        //        //
        //        iClassStyle = ClassStyle;
        //        if (string.IsNullOrEmpty(iClassStyle)) {
        //            iClassStyle = "ccPanel";
        //        }
        //        //If IsArray(Cells) Then
        //        ColumnCount = Cells.GetUpperBound(1);
        //        //End If
        //        RQS = cp.Doc.RefreshQueryString;
        //        //
        //        SortColPtr = AdminUIController.GetReportSortColumnPtr(cp, DefaultSortColumnPtr);
        //        SortColType = AdminUIController.GetReportSortType(cp);
        //        //
        //        // ----- Start the table
        //        //
        //        Content.Append(HtmlController.tableStart(3, 1, 0));
        //        //
        //        // ----- Header
        //        //
        //        Content.Append("\r\n<tr>");
        //        Content.Append(AdminUIController.getReport_CellHeader(cp, 0, "&nbsp", "50px", "Right", "ccAdminListCaption", RQS, SortingStateEnum.NotSortable));
        //        for (ColumnPtr = 0; ColumnPtr < ColumnCount; ColumnPtr++) {
        //            ColumnWidth = ColWidth[ColumnPtr];
        //            if (!ColSortable[ColumnPtr]) {
        //                //
        //                // not sortable column
        //                //
        //                Content.Append(AdminUIController.getReport_CellHeader(cp, ColumnPtr, ColCaption[ColumnPtr], ColumnWidth, ColAlign[ColumnPtr], "ccAdminListCaption", RQS, SortingStateEnum.NotSortable));
        //            } else if (ColumnPtr == SortColPtr) {
        //                //
        //                // This is the current sort column
        //                //
        //                Content.Append(AdminUIController.getReport_CellHeader(cp, ColumnPtr, ColCaption[ColumnPtr], ColumnWidth, ColAlign[ColumnPtr], "ccAdminListCaption", RQS, (SortingStateEnum)SortColType));
        //            } else {
        //                //
        //                // Column is sortable, but not selected
        //                //
        //                Content.Append(AdminUIController.getReport_CellHeader(cp, ColumnPtr, ColCaption[ColumnPtr], ColumnWidth, ColAlign[ColumnPtr], "ccAdminListCaption", RQS, SortingStateEnum.SortableNotSet));
        //            }

        //            //If ColumnPtr = SortColPtr Then
        //            //    '
        //            //    ' This column is currently the active sort
        //            //    '
        //            //    Call Content.Append(GetReport_CellHeader(ColumnPtr, ColCaption(ColumnPtr), ColumnWidth, ColAlign(ColumnPtr), "ccAdminListCaption", RQS, SortColType))
        //            //Else
        //            //    Call Content.Append(GetReport_CellHeader(ColumnPtr, ColCaption(ColumnPtr), ColumnWidth, ColAlign(ColumnPtr), "ccAdminListCaption", RQS, SortingStateEnum.SortableNotSet))
        //            //End If
        //        }
        //        Content.Append("\r\n</tr>");
        //        //
        //        // ----- Data
        //        //
        //        if (RowCount == 0) {
        //            Content.Append("\r\n<tr>");
        //            Content.Append(getReport_Cell(cp, (RowBAse + RowPointer).ToString(), "right", 1, RowPointer));
        //            Content.Append(getReport_Cell(cp, "-- End --", "left", ColumnCount, 0));
        //            Content.Append("\r\n</tr>");
        //        } else {
        //            RowBAse = (ReportPageSize * (ReportPageNumber - 1)) + 1;
        //            for (RowPointer = 0; RowPointer < RowCount; RowPointer++) {
        //                Content.Append("\r\n<tr>");
        //                Content.Append(getReport_Cell(cp, (RowBAse + RowPointer).ToString(), "right", 1, RowPointer));
        //                for (ColumnPtr = 0; ColumnPtr < ColumnCount; ColumnPtr++) {
        //                    Content.Append(getReport_Cell(cp, Cells[RowPointer, ColumnPtr], ColAlign[ColumnPtr], 1, RowPointer));
        //                }
        //                Content.Append("\r\n</tr>");
        //            }
        //        }
        //        //
        //        // ----- End Table
        //        //
        //        Content.Append(Constants.kmaEndTable);
        //        result += Content.ToString();
        //        //
        //        // ----- Post Table copy
        //        //
        //        if ((DataRowCount / (double)ReportPageSize) != Math.Floor((DataRowCount / (double)ReportPageSize))) {
        //            PageCount = encodeInteger((DataRowCount / (double)ReportPageSize) + 0.5);
        //        } else {
        //            PageCount = encodeInteger(DataRowCount / (double)ReportPageSize);
        //        }
        //        if (PageCount > 1) {
        //            result += "<br>Page " + ReportPageNumber + " (Row " + (RowBAse) + " of " + DataRowCount + ")";
        //            if (PageCount > 20) {
        //                PagePointer = ReportPageNumber - 10;
        //            }
        //            if (PagePointer < 1) {
        //                PagePointer = 1;
        //            }
        //            if (PageCount > 1) {
        //                result += "<br>Go to Page ";
        //                if (PagePointer != 1) {
        //                    WorkingQS = cp.Doc.RefreshQueryString;
        //                    WorkingQS = modifyQueryString(WorkingQS, "GotoPage", "1", true);
        //                    result += "<a href=\"?" + WorkingQS + "\">1</A>...&nbsp;";
        //                }
        //                WorkingQS = cp.Doc.RefreshQueryString;
        //                WorkingQS = modifyQueryString(WorkingQS, RequestNamePageSize, ReportPageSize.ToString(), true);
        //                while ((PagePointer <= PageCount) && (LinkCount < 20)) {
        //                    if (PagePointer == ReportPageNumber) {
        //                        result += PagePointer + "&nbsp;";
        //                    } else {
        //                        WorkingQS = modifyQueryString(WorkingQS, RequestNamePageNumber, PagePointer.ToString(), true);
        //                        result += "<a href=\"?" + WorkingQS + "\">" + PagePointer + "</A>&nbsp;";
        //                    }
        //                    PagePointer ++;
        //                    LinkCount ++;
        //                }
        //                if (PagePointer < PageCount) {
        //                    WorkingQS = modifyQueryString(WorkingQS, RequestNamePageNumber, PageCount.ToString(), true);
        //                    result += "...<a href=\"?" + WorkingQS + "\">" + PageCount + "</A>&nbsp;";
        //                }
        //                if (ReportPageNumber < PageCount) {
        //                    WorkingQS = modifyQueryString(WorkingQS, RequestNamePageNumber, (ReportPageNumber + 1).ToString(), true);
        //                    result += "...<a href=\"?" + WorkingQS + "\">next</A>&nbsp;";
        //                }
        //                result += "<br>&nbsp;";
        //            }
        //        }
        //        //
        //        result = ""
        //        + PreTableCopy + "<table border=0 cellpadding=0 cellspacing=0 width=\"100%\"><tr><td style=\"padding:10px;\">"
        //        + result + "</td></tr></table>"
        //        + PostTableCopy + "";
        //    } catch (Exception) {
        //        throw;
        //    }
        //    return result;
        //}
        //
        //====================================================================================================
        public static string getBody(CPBaseClass cp, string Caption, string ButtonListLeft, string ButtonListRight, bool AllowAdd, bool AllowDelete, string Description, string ContentSummary, string Content) {
            string result = "";
            string LeftButtons = "";
            string RightButtons = "";
            string CellContentSummary = "";
            //
            // Build ButtonBar
            //
            if (!string.IsNullOrEmpty(ButtonListLeft.Trim(' '))) {
                LeftButtons = getButtonsFromList( ButtonListLeft, AllowDelete, AllowAdd);
            }
            if (!string.IsNullOrEmpty(ButtonListRight.Trim(' '))) {
                RightButtons = getButtonsFromList( ButtonListRight, AllowDelete, AllowAdd);
            }
            string ButtonBar = getButtonBar(LeftButtons, RightButtons);
            if (!string.IsNullOrEmpty(ContentSummary)) {
                CellContentSummary = ""
                    + "\r<div class=\"ccPanelBackground\" style=\"padding:10px;\">"
                    + getPanel(ContentSummary, "ccPanel",  "100%", 5)
                    + "\r</div>";
            }
            result += ""
                + ButtonBar
                + "<div class=\"p-2\">"
                + getTitleBar(Caption, Description)
                + CellContentSummary
                + "</div>"
                + "<div>" + Content + "</div>"
                + ButtonBar;
            result = HtmlController.formMultipart(cp, result, cp.Doc.RefreshQueryString, "", "ccForm");
            return result;
        }

    }
}
